coder:
  service:
    type: ClusterIP
  ingress:
    enable: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: selfsigned
  # external-dns annotations removed (not using ExternalDNS)
    host: coder.homelab.local
    tls:
      enable: true
      secretName: coder.homelab.local
  env:
  - name: "CODER_ACCESS_URL"
    value: "https://coder.homelab.local"
  - name: CODER_PG_CONNECTION_URL
    valueFrom:
      secretKeyRef:
        name: postgres-secret
        key: coder-psql