defaultPodOptions:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0

controllers:
  main:
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/prowlarr
          tag: 2.3.5.5327-ls142
          pullPolicy: IfNotPresent
        env:
          TZ: America/Toronto
          PUID: "0"
          PGID: "0"

service:
  main:
    controller: main
    ports:
      http:
        port: 9696

ingress:
  main:
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: mkcert
    hosts:
      - host: prowlarr.homelab.local
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - secretName: prowlarr.homelab.local
        hosts:
          - prowlarr.homelab.local

persistence:
  config:
    type: persistentVolumeClaim
    storageClass: local-path
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: true
    globalMounts:
      - path: /config
