apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: setup
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: argocd
    server: '*'
  - namespace: cert-manager
    server: '*'
  - namespace: external-secrets
    server: '*'
  - namespace: k8s-gateway
    server: '*'
  - namespace: metallb-system
    server: '*'
  - namespace: ingress-nginx
    server: '*'
  - namespace: kube-system
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false
  roles:
