apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prowlarr
  namespace: argocd
spec:
  project: internal
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
  - chart: prowlarr
    repoURL: https://bjw-s.github.io/helm-charts
    targetRevision: 5.4.1
    helm:
      valueFiles:
      - $values/configs/internal/prowlarr/values.yaml
  - repoURL: https://github.com/dhpup/homelab.git
    targetRevision: main
    ref: values
  destination:
    name: in-cluster
    namespace: prowlarr
