apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smtp
  namespace: argocd
spec:
  project: internal
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
  - repoURL: https://github.com/dhpup/homelab.git
    targetRevision: main
    path: configs/internal/smtp
  destination:
    name: in-cluster
    namespace: smtp

