apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: git-ssh-secret
spec:
  target:
    name: git-ssh-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        id_ed25519: |-
          {{ .id_ed25519 }}
  data:
    - secretKey: id_ed25519
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: f235940f-8a16-4a47-a367-b37d004bcb7e
        property: b64_id_ed25519
        decodingStrategy: Base64
