apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-pvc
  namespace: nzbget
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path
