env:
  TZ: America/Toronto
  PUID: 0
  PGUID: 0
  THREADS_WORKER_INIT_TIMEOUT: 200000

image:
  tag: 2.13.01
  repository: haveagitgat/tdarr

service:
  server:
    enabled: true
    type: LoadBalancer
    annotations:
      metallb.universe.tf/address-pool: bgp-pool
      coredns.io/hostname: server.tdarr.home.homelab.local
    externalTrafficPolicy: Local
    ports:
      controller-lb:
        enabled: true
        port: 8266
        nodePort: 8266
        targetPort: 8266
        protocol: TCP

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: selfsigned
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.0.0/16,172.16.0.0/12"
      # external-dns annotation removed (not using ExternalDNS)
    hosts:
      - host: tdarr.home.homelab.local
        paths:
        - path: /
          pathType: Prefix
    tls:
    - secretName: tdarr.home.homelab.local
      hosts:
      - tdarr.home.homelab.local

node:
  enabled: true
  id: k8s-node
  image:
    tag: 2.13.01
  resources:
    limits:
      cpu: 4
      memory: 4Gi
    requests:
      cpu: 1m
      memory: 1Mi

persistence:
  config:
    enabled: true
    nameOverride: local-path-config
    storageClass: local-path
    size: 10Gi
    accessMode: ReadWriteOnce
  data:
    enabled: true
    nameOverride: local-path-data
    storageClass: local-path
    size: 30Gi
    accessMode: ReadWriteOnce
  media:
    enabled: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0

probes:
  startup:
    spec:
      failureThreshold: 2000

initContainers:
  skip-chown:
    image: busybox:1.28
    command: ['sh', '-c', "touch /firstRun"]
