image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/paperless-ngx/paperless-ngx
  tag: 2.18.1

env:
  PAPERLESS_TIME_ZONE: America/New_York
  PAPERLESS_OCR_LANGUAGE: eng
  PAPERLESS_CONSUMER_POLLING: 60
  PAPERLESS_REDIS: redis://paperless-redis-headless:6379

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: selfsigned
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      # nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.0.0/16,172.16.0.0/12"
      nginx.ingress.kubernetes.io/proxy-body-size: 1024m
  # external-dns annotation removed (not using ExternalDNS)

    hosts:
      - host: paperless.homelab.local
        paths:
        - path: /
          pathType: Prefix
    tls:
    - secretName: paperless.homelab.local
      hosts:
      - paperless.homelab.local

persistence:
  consume:
     enabled: false
     # type: nfs
     # server: "192.168.1.10"
     # path: /Media/Paperless-Consumer
     # mountPath: /usr/src/paperless/consume
  data:
    enabled: true
    nameOverride: local-path-data
    storageClass: local-path
    size: 100Gi
  media:
    enabled: true
    nameOverride: local-path-media
    storageClass: local-path
    size: 25Gi
    mountPath: /usr/src/paperless/media
  export:
    enabled: true
    nameOverride: local-path-export
    storageClass: local-path
    size: 25Gi
    mountPath: /usr/src/paperless/export

redis:
  enabled: true

  image:
    pullPolicy: IfNotPresent
    repository: library/redis
    tag: 6.2.6

  # Ensure subchart override: set redis.image.* used by dependent charts
  imageOverride:
    repository: library/redis
    tag: 6.2.6

  architecture: standalone
  auth:
    enabled: false

  master:
    persistence:
      enabled: false

# Enable an embedded PostgreSQL for local k3d testing (no PV to keep it simple)
postgresql:
  enabled: true
  postgresqlDatabase: paperless
  postgresqlUsername: paperless
  postgresqlPassword: changeme
  persistence:
    enabled: false
  image:
    repository: postgres
    tag: "11"
