apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: requestrr
  namespace: requestrr
spec:
  ingressClassName: nginx
  rules:
  - host: requestrr.homelab.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: requestrr
            port:
              number: 4545
