apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unpackerr-secrets
  namespace: unpackerr
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  target:
    name: unpackerr-secret
    creationPolicy: Owner
  data:
  - secretKey: UN_SONARR_0_API_KEY
    remoteRef:
      key: sonarr_api_key
  - secretKey: UN_RADARR_0_API_KEY
    remoteRef:
      key: radarr_api_key
