defaultPodOptions:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0

controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/unpackerr/unpackerr
          tag: 0.15.2
          pullPolicy: IfNotPresent
        env:
          TZ: America/Toronto
          UN_SONARR_0_URL: http://sonarr.sonarr.svc.cluster.local:8989
          UN_SONARR_0_PATHS_0: /downloads
          UN_RADARR_0_URL: http://radarr.radarr.svc.cluster.local:7878
          UN_RADARR_0_PATHS_0: /downloads
        envFrom:
          - secretRef:
              name: unpackerr-secret

service:
  main:
    controller: main
    ports:
      http:
        port: 5656

persistence:
  downloads:
    type: hostPath
    hostPath: /homelab-storage/downloads
    hostPathType: Directory
    globalMounts:
      - path: /downloads
