defaultPodOptions:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0

controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/k8s-at-home/nzbget
          tag: v21.1
          pullPolicy: IfNotPresent
        env:
          TZ: America/Toronto

service:
  main:
    controller: main
    ports:
      http:
        port: 6789

ingress:
  main:
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: mkcert
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    hosts:
      - host: nzbget.homelab.local
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - secretName: nzbget.homelab.local
        hosts:
          - nzbget.homelab.local

persistence:
  config:
    existingClaim: nzbget-config
    globalMounts:
      - path: /config