defaultPodOptions:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0

controllers:
  main:
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/nzbget
          tag: v26.1-ls239
          pullPolicy: IfNotPresent
        env:
          TZ: America/Toronto
          PUID: "0"
          PGID: "0"

service:
  main:
    controller: main
    ports:
      http:
        port: 6789

ingress:
  main:
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: mkcert
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    hosts:
      - host: nzbget.homelab.local
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - secretName: nzbget.homelab.local
        hosts:
          - nzbget.homelab.local

persistence:
  config:
    type: persistentVolumeClaim
    storageClass: local-path
    accessMode: ReadWriteOnce
    size: 5Gi
    globalMounts:
      - path: /config