apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: setup
  syncPolicy:
    automated: {}
    syncOptions:
      - ServerSideApply=true
  sources:
  - chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.18.5
    helm:
      releaseName: sealed-secrets-controller
      valueFiles:
      - $values/configs/setup/sealed-secrets/values.yaml
  - repoURL: https://github.com/dhpup/homelab.git
    targetRevision: main
    ref: values
  destination:
    name: in-cluster
    namespace: kube-system
