apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: setup
  syncPolicy:
  sources:
  - repoURL: https://github.com/dhpup/homelab.git
    targetRevision: main
    path: configs/setup/sealed-secrets
  destination:
    name: in-cluster
    namespace: kube-system
