defaultPodOptions:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0

controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/onedr0p/bazarr
          tag: 1.4.2
          pullPolicy: IfNotPresent
        env:
          TZ: America/Toronto

service:
  main:
    controller: main
    ports:
      http:
        port: 6767

ingress:
  main:
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: mkcert
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    hosts:
      - host: bazarr.homelab.local
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - secretName: bazarr.homelab.local
        hosts:
          - bazarr.homelab.local

persistence:
  config:
    type: persistentVolumeClaim
    storageClass: local-path
    accessMode: ReadWriteOnce
    size: 50Gi
    globalMounts:
      - path: /config
