defaultPodOptions:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0

controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/maintainerr/maintainerr
          tag: 3.18.0
          pullPolicy: IfNotPresent
        env:
          TZ: America/Toronto

service:
  main:
    controller: main
    ports:
      http:
        port: 6246

ingress:
  main:
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: mkcert
    hosts:
      - host: maintainerr.homelab.local
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - secretName: maintainerr.homelab.local
        hosts:
          - maintainerr.homelab.local

persistence:
  data:
    type: persistentVolumeClaim
    storageClass: local-path
    accessMode: ReadWriteOnce
    size: 5Gi
    retain: true
    globalMounts:
      - path: /opt/data
