image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/onedr0p/sonarr
  tag: 3.0.10.1567

env:
  TZ: America/Toronto

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: selfsigned
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 1024m
      # external-dns annotation removed (not using ExternalDNS)
    hosts:
      - host: sonarr.homelab.local
        paths:
        - path: /
          pathType: Prefix
    tls:
    - secretName: sonarr.homelab.local
      hosts:
      - sonarr.homelab.local

persistence:
  media:
    enabled: true
    type: hostPath
    hostPath: /Users/daneko/homelab-storage/tv
    mountPath: /tv
  downloads:
    enabled: true
    type: hostPath
    hostPath: /Users/daneko/homelab-storage/downloads
    mountPath: /homelab-storage/downloads
  nzbget:
    enabled: true
    # Switched from NFS to a PVC backed by local-path for local k3d clusters
    type: pvc
    name: nzbget-pvc
    accessMode: ReadWriteOnce
    mountPath: /nzbget
    storageClass: local-path
    size: 50Gi
  config:
    enabled: true
    storageClass: local-path
    size: 50Gi

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0
