defaultPodOptions:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0

controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/home-operations/sonarr
          tag: 4.0.17.2953
          pullPolicy: IfNotPresent
        env:
          TZ: America/Toronto

service:
  main:
    controller: main
    ports:
      http:
        port: 8989

ingress:
  main:
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: mkcert
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    hosts:
      - host: sonarr.homelab.local
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - secretName: sonarr.homelab.local
        hosts:
          - sonarr.homelab.local

persistence:
  config:
    type: persistentVolumeClaim
    storageClass: local-path
    accessMode: ReadWriteOnce
    size: 50Gi
    globalMounts:
      - path: /config
  media:
    type: hostPath
    hostPath: /homelab-storage/tv
    hostPathType: Directory
    globalMounts:
      - path: /tv
  downloads:
    type: hostPath
    hostPath: /homelab-storage/downloads
    hostPathType: Directory
    globalMounts:
      - path: /homelab-storage/downloads
  nzbget:
    type: persistentVolumeClaim
    storageClass: local-path
    accessMode: ReadWriteOnce
    size: 50Gi
    globalMounts:
      - path: /nzbget
