apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kargo-admin-credentials
  namespace: kargo
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  target:
    name: kargo-admin-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: ADMIN_ACCOUNT_PASSWORD_HASH
    remoteRef:
      key: kargo_admin_password_hash
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      nullBytePolicy: Ignore
  - secretKey: ADMIN_ACCOUNT_TOKEN_SIGNING_KEY
    remoteRef:
      key: kargo_token_signing_key
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      nullBytePolicy: Ignore
