defaultPodOptions:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0

controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/k8s-at-home/radarr
          tag: v4.1.0.6175
          pullPolicy: IfNotPresent
        env:
          TZ: America/Toronto

service:
  main:
    controller: main
    ports:
      http:
        port: 7878

ingress:
  main:
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: mkcert
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    hosts:
      - host: radarr.homelab.local
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - secretName: radarr.homelab.local
        hosts:
          - radarr.homelab.local

persistence:
  config:
    existingClaim: radarr-config
    globalMounts:
      - path: /config
  media:
    type: hostPath
    hostPath: /homelab-storage/movies
    hostPathType: Directory
    globalMounts:
      - path: /movies
  downloads:
    type: hostPath
    hostPath: /homelab-storage/downloads
    hostPathType: Directory
    globalMounts:
      - path: /homelab-storage/downloads
  nzbget:
    existingClaim: radarr-nzbget
    globalMounts:
      - path: /nzbget
