defaultPodOptions:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0

controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/home-operations/radarr
          tag: 6.2.0.10390
          pullPolicy: IfNotPresent
        env:
          TZ: America/Toronto

service:
  main:
    controller: main
    ports:
      http:
        port: 7878

ingress:
  main:
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: mkcert
    hosts:
      - host: radarr.homelab.local
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - secretName: radarr.homelab.local
        hosts:
          - radarr.homelab.local

persistence:
  config:
    type: persistentVolumeClaim
    storageClass: local-path
    accessMode: ReadWriteOnce
    size: 50Gi
    retain: true
    globalMounts:
      - path: /config
  media:
    type: hostPath
    hostPath: /homelab-storage/movies
    hostPathType: Directory
    globalMounts:
      - path: /movies
  downloads:
    type: hostPath
    hostPath: /homelab-storage/downloads
    hostPathType: Directory
    globalMounts:
      - path: /downloads

