apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: requestrr
  namespace: argocd
spec:
  project: external
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/dhpup/homelab.git
    targetRevision: main
    path: configs/external/requestrr
  destination:
    name: in-cluster
    namespace: requestrr
