image:
  repository: docker.seadrive.org/seafileltd/seafile-pro-mc
  tag: 9.0.5

imagePullSecrets:
  - name: image-pull-secret

env:
  SEAFILE_ADMIN_EMAIL: noah@homelab.local
  SEAFILE_SERVER_HOSTNAME: seafile.homelab.local
  SEAFILE_ADMIN_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: seafile-sealed-secret
        key: SEAFILE_ADMIN_PASSWORD
  DB_ROOT_PASSWD:
    valueFrom:
      secretKeyRef:
        name: seafile-sealed-secret
        key: DB_ROOT_PASSWD

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 1024m
      external-dns.alpha.kubernetes.io/target: 'homelab.local'
      external-dns.alpha.kubernetes.io/cloudflare-proxied: 'true'

    hosts:
      - host: seafile.homelab.local
        paths:
        - path: /
          pathType: Prefix
    tls:
    - secretName: seafile.homelab.local
      hosts:
      - seafile.homelab.local
  sso:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/permanent-redirect: "https://seafile.homelab.local/sso/?next=/"
    hosts:
      - host: seafile.homelab.local
        paths:
        - path: /accounts/login/
          pathType: Prefix
    tls:
    - secretName: seafile.homelab.local
      hosts:
      - seafile.homelab.local

persistence:
  shared:
    enabled: true
    nameOverride: longhorn-rwo
    type: pvc
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 1Ti

mariadb:
  enabled: true
  architecture: standalone
  auth:
    database: seafile
    username: seafile
    existingSecret: seafile-sealed-secret
  primary:
    persistence:
      enabled: true
      storageClass: longhorn
      size: 25Gi