defaultPodOptions:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0

controllers:
  main:
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/sabnzbd
          tag: 4.5.5-ls249
          pullPolicy: IfNotPresent
        env:
          TZ: America/Toronto
          PUID: "0"
          PGID: "0"

service:
  main:
    controller: main
    ports:
      http:
        port: 8080

ingress:
  main:
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: mkcert
    hosts:
      - host: sabnzbd.homelab.local
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - secretName: sabnzbd.homelab.local
        hosts:
          - sabnzbd.homelab.local

persistence:
  config:
    type: persistentVolumeClaim
    storageClass: local-path
    accessMode: ReadWriteOnce
    size: 5Gi
    retain: true
    globalMounts:
      - path: /config
  downloads:
    type: hostPath
    hostPath: /homelab-storage/downloads
    hostPathType: Directory
    globalMounts:
      - path: /homelab-storage/downloads
