externalURL: https://registry.homelab.local

expose:
  type: ingress
  ingress:
    hosts:
      core: registry.homelab.local
    annotations:
      cert-manager.io/cluster-issuer: selfsigned
      # cert-manager.io/cluster-issuer: selfsigned
      # external-dns annotations removed (not using ExternalDNS)
  tls:
    certSource: secret
    secret:
      secretName: registry.homelab.local-tls

trivy:
  enabled: false
notary:
  enabled: false

persistence:
  persistentVolumeClaim:
    registry:
      existingClaim: registry
    chartmuseum:
      existingClaim: chartmuseum
    jobservice:
      jobLog:
        existingClaim: jobservice
    database:
      existingClaim: database
    redis:
      existingClaim: redis

updateStrategy:
  type: Recreate

existingSecretSecretKey: harbor-secrets
existingSecretAdminPasswordKey: harbor-secrets

registry:
  credentials:
    username: root
    existingSecret: harbor-secrets
