apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: doplarr-secrets
  namespace: doplarr
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  target:
    name: doplarr-secret
    creationPolicy: Owner
  data:
  - secretKey: DISCORD__TOKEN
    remoteRef:
      key: discord_bot_token
  - secretKey: OVERSEERR__API
    remoteRef:
      key: seerr_api_key
