---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    github-token: AgAZRbr4DJHCWwAIbXt+hVC5FxSgpu8vSisM4p7HuWyqRW8mU2BeITm4OYx+7jQc6UsYYAdEX6LW/oONXDzpzgsdsp3aevDXnkSZIY38P/JMAov4z6ECg5crIs1CArMWBFqk/vWpqwhWf5aA8BtJ7pOadE412Htbq/HoMSCQ8+i9j5D2F09bOhws23uBsUE2N/ivHE8wjayls3MSi99EVlcCgJs21As18s3bsO2WWmQAZeaHEPjkIBXf2R1AMEx8zGNxKrtfAcHHgIFuzxmznnM5lUBeBfRb8qj0gPNq7Ej2MEuhDXN2ogOBHiAubmo/6T34Va8hcMTLm1E65X5tyq+A6oL9welIkgWJdBmcpG/Y/R/Kn+Eo6SrWWsAHyWaVFebeVNjzGDdhXZx4FY89rVqjACUJV9/f0usyu8rQJRsD4m2WlQMdcV/68ZJvx58ja5X7O/qWFKZMwm/sggDJdFxlQQD+Urjw147fPkqEWw/2+96A/aTqxTpBwtamnLeKNPxEBKnCG72G3yf74pITyKVR8ohSrwav7B/UscgmRTlyzVPSHm9Q8wAB2alCRHP8UdcsTUjzObnVbXQcZ98tKT3zBdWnsM9JB8LTkGNsXWge6qMd+yxIcmC9Mulo+VnxpU+6dvApslvpQ0M8NZO3vWL9phMioyt33onIMGE6dIB2QKk2+Y5MoFnloRE3p8SIp+CV83oJfOX8GSY1c6DlkdY8qeEZh/4D0QCQOUcijjslxqWSA48UmHFGTi+7Ns44P7pTr8uD5AdTF0iwH7LOkgvjeQbhEYO7AXeDao/5TwnfosVRVWRoxyYyNVVboho=
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
