---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-credentials
  namespace: argocd
spec:
  encryptedData:
    password: AgBZhKAyGmIiFl+9FxpMrjRDPXokHcW2cmW+/42M8PpJfvwDAnU6DgCjXSAEFdZsVNrVkFtXtrQpxHGUPMfgVa6YbbS7+fWj2UvBusiIL3ETRKMSy4wa0QnxaRyJ3s5Ysqgjy1MH4m6psVI9PVnCBaOxrporKPX5v1jf+ow0JocvMASSbKIDbjEuAoeK1XiVRK2gwAJm72E1mMliMKBdj+arXCLxBoJVBB/XDhwADNN67NBG9Lkn9TUbDsKzqv5ZCrDOxuZvOrJTHm6PJcrgrHia7kaj9QI1NpW0zY6zCKyNGxhn0b+vzD6QOrH0Pas5/tTiu3giPuqtec+YWvpqmzS28rQkeqelkhtJXWYNTd6YEPx5wt9qIRBWk0dzLGTe6raM6pmUNkVmwqMKMdx+Y0i21SVO+io4yjMcd5EEutc6qSkt12/XvM+mxvlMI7RSe0xtfU2MoJWdy0tkiujmg+SI3BnWglNvQLJ41dxr5//ugRgCFSK4wqgJ21ySFc9Pctd3qvbrJ+yDLRuR0Juonapeafy99Sm5Dg/BAl16SC33Ruts9tTloC7Zq04zcj9TDTH4l0fneQQcsvLFi9t4pMvvSi+1FwQorKWPOwql1z9F6dpN/1QNpJtwK4aDJXcsDxV7yNjU096RQOcqc7ACV0ocDHSHqu6Ek51Jgmf+t0gf1y3Ismzksa5rxDt7P1ABqBmsYRxHekIt+U/kPZ3YJI4HYHlN/p0+DSyK8oNx8ChOI/WzzYfcI07pCM1JZdYifqnBBwAWQH+XBV1iGXaF2Na9cQdpezcZKLAB8SRUiU12UZjEqpyrSe7Bm5SQsUI=
    username: AgAjSHoOJlqsYA0FPkB5wd3R0fO3qhev7FRNcMSxEMbuOqpbrYMvRkJDf8jGCvD+MA9u43e652dqYHXSrAYixzVfT0+CKGjOwCqoDRiMtSy6bGzDqatI873EWoXynivuPKfbqqEAvwk1C/KWbDHbbntry67YL3p1iQutMYL7tgMgBuQsQ/bCks9Q3S9/oKUfbRgNBVZ8l0EvPsXnGB9WkheVFojWV/1xLgxNA/MAJuBtzqiw+1UErB8DIYLV5wurk5bfRqzROdUl0aT1L9kYXVbrOHhQzUoMr/2CWbBcgkZstqex4VdzvNn/7I38mc7wyC96dCqmP50rv+y9e9Ytzxuu1gaHMA9M8tbjsLvsbipDS5MqvIERN1RmgmIToqntEaQMl/J30lbDIi0CO0ZLRASreci2Gnjr5FWnxduPY3BQ0v8pFPAvfM2EFJw8Trk8WsH/2eLJgqQsk7g7JSHaZgPi/W9Z8IsRfaY+R7u2JqUnVJAVrSCWeMnyEV5maRvOYGI0IocURVM1TSg+A5GfAA/RUZ2azEvUTox3j4FYKxMtryb2OOCAmnDOfBlfsrJGqfna3LVbpMOA6L5q0GvxCskpYzCoQUQ09/XlVJBbtIs22Bpxxi5Xd3Vlugc5z//rldz5ZxTvLDJHpDzf/2tobvs0M42cnEQu4iFUMqtuDeKM5/LWitAfjv3qdTjKheCR15irIWYTeA==
  template:
    metadata:
      name: github-credentials
      namespace: argocd
