---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-credentials
  namespace: argocd
spec:
  encryptedData:
    password: AgABXRxWpbSHA/9QdC3QagRf4Of+10OOULyNjJeE/nKnkzwd07qWNpO+SPBOYt82rVYgtYZm3NobfZ4TGRGjHOe+P1OSNSK2JxxvmttRvQuAJ30kUN/yZxDgqfazqAI7sfZhb/sRc9rNEEsnaJJGNoIaD5vHCq0Ci2uD95TzG8OUoFpg+Uus2K8lHzkARa886pgp83jFIkqRJ8v9XwsF3U2l3/he3/6w4mjUMlIjaO1H+Vv8xFCusUfeevNcyredgcsv2TlVFxDisNHWd0R4YgV6w5clJJoeTCSxAKtvx5jRhlrE8j/lUApuqLVq9dMokjwwvB8xiRX2tNbo6qUz+rYQb63ZyOWMQNi694KBhGZckArBA0Jcx6Kco3Ut9np3VKF25Vd+yWck0uoapCey493sNHhlGoqBkZ+gaPr0BfyIoYNuXfgIzsCsScwC4nO9OQKNOq3NTmLUMtf7LkXMN7Ih/vSe0cPXx5TdWME2hWDS/JZYfeppFUH5touKpwMQBZHtZyym/Ue4KXb9r3RO5Zl/BkljRTWVmnlCeHNUW0ruSS3BqPkdqgdB+D/HbDVobK7cpcSQD9ebIvqQsIQ503cOlQQzgfgRvhh6CJ+AXUWgWm97y4NoxDRdPLy90SfYMScpHIRKFywjAL/hQ3CZMxmpepXdwyplW9LbZgmnsPOsgUkWwDloQj2l32hBEMfM4MoS5UIosYiIYwP8dhd7L4B534Kz5Oj+6nclEbqvDwHB/ZAb2rUshXhJZya3C3eePWLMQUgG6lJJnAoc+xHv1S30oxw0GF/JtDs8G4XpexmQWqWbMsIZJqYwPdl4ZJ0=
    username: AgCFCG/fksJiRoOyRF7NmxQxV9bBzpMqaUL0m9UwQb1Nb3gpEF4pZ4BL8zulSCrRA7hAaK+ZGtXQ8T0xSimo4t/BY/abM3w1FP9B7FeyzVVbCdGcXGGIXMvW9SfH0cLBQa7dBhx1O3bsCoH3xGVgVoque4u7q+2RnjJuTVVxipVeqUTWJtfvv5vlQgMR9U4xT8QWBFoCem7qk6j0wBeeO/jvY0UQi5fAk0q1n6dHUK2qcQoFMZ7kvJPVJNmfZT9JD63qpbBvB8drfNqjfPjVCDu4bLakfdxLWgx+6Q9zXdnZyTmzGBd/DdkiXw8Ri9VAV575TKnYYtPNjH2vezxIPKC8ads6F6bU2Vkfbz96kDpCxDxOHROOz4uNxlKod8bah+/w6b9umhw2bMAGbMl+irO4FL32gaA4PJgg+T3xIEVEJyrAiYbABkoHObaLaor5iPDEXLEeqRyGfYQ70sd3GG63a4rLfDxEkN6kFou4FJBWNaxcdg1pYI365wow0GH3hGcdmVohNAIfvfKOqOlZBbGU6C4QzYemRW6q53oJHqO377PtHrU+Mz9fIvP4BdL2SQMq8rVThVBrUKnxvL9Ip9T01uYDT+s6tQRmtrkYMJqMyvt+CtizE53U2WEoAM1VSxAh9cVSlzqkFLa4pBLqgFwXheM0Qj8CURQruFhE95nnpoB29/XKPyDXEU5JZvUiHbUdwYFKpw==
  template:
    metadata:
      name: github-credentials
      namespace: argocd
