apiVersion: v1
kind: Secret
metadata:
  name: paperless-postgres-secret
  namespace: paperless
stringData:
  POSTGRES_USER: paperless
  POSTGRES_PASSWORD: changeme
  POSTGRES_DB: paperless
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-postgres
  namespace: paperless
spec:
  selector:
    matchLabels:
      app: paperless-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: paperless-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: paperless-postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: paperless-postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: paperless-postgres-secret
              key: POSTGRES_DB
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pgdata
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: paperless-postgres
  namespace: paperless
spec:
  selector:
    app: paperless-postgres
  ports:
  - port: 5432
    targetPort: 5432
