apiVersion: v1
kind: ConfigMap
metadata:
  name: recyclarr-config
  namespace: recyclarr
data:
  recyclarr.yml: |
    sonarr:
      series:
        base_url: http://sonarr.sonarr.svc.cluster.local:8989
        api_key: !env_var SONARR_API_KEY
        delete_old_custom_formats: true
        include:
          - template: web-1080p
    radarr:
      movies:
        base_url: http://radarr.radarr.svc.cluster.local:7878
        api_key: !env_var RADARR_API_KEY
        delete_old_custom_formats: true
        include:
          - template: hd-bluray-web
