apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recyclarr-secrets
  namespace: recyclarr
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  target:
    name: recyclarr-secret
    creationPolicy: Owner
  data:
  - secretKey: SONARR_API_KEY
    remoteRef:
      key: sonarr_api_key
  - secretKey: RADARR_API_KEY
    remoteRef:
      key: radarr_api_key
